name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'
  workflow_dispatch: 

jobs:
  trigger-vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
